DROP TABLE IF EXISTS alerts;

CREATE TABLE IF NOT EXISTS alerts (
    alert_id VARCHAR(64) PRIMARY KEY COMMENT 'Alert ID (generated by MD5)',
    patient_id VARCHAR(32) NOT NULL COMMENT 'Patient ID',
    alert_time DATETIME NOT NULL COMMENT 'Alert time',
    alert_type VARCHAR(64) NOT NULL COMMENT 'Alert type (heart_rate/blood_oxygen/etc.)',
    alert_detail VARCHAR(256) NOT NULL COMMENT 'Alert details',
    alert_level VARCHAR(16) NOT NULL COMMENT 'Alert level (level1/level2)',
    handle_status VARCHAR(16) DEFAULT 'pending' COMMENT 'Handling status: pending/confirmed/resolved',
    handle_time DATETIME COMMENT 'Handling time',
    handle_by VARCHAR(32) DEFAULT 'admin' COMMENT 'Handler',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP() COMMENT 'Synchronization time',
    INDEX idx_patient_id (patient_id),
    INDEX idx_alert_time (alert_time),
    INDEX idx_handle_status (handle_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
