{
 "title": "Apache Flink Dashboard",
 "description": "Dashboard for Job Manager and Task Manager",
 "tags": [
  "flink",
  "task manager",
  "job manager",
  "apache"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   { "name": "tm_id", "label": "Task Manager", "query": { "query": "label_values(tm_id)" } },
   {
    "name": "jm_instance",
    "label": "Job Manager",
    "query": {
     "query": "label_values(flink_jobmanager_numRegisteredTaskManagers,instance)"
    }
   },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{tm_id=~\"$tm_id\"},job_name)"
    }
   },
   {
    "name": "task_name",
    "label": "Task Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{job_name=~\"$job_name\"},task_name)"
    }
   },
   { "name": "ad_hoc", "label": "Ad Hoc" }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Source Throughput (rows/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Source Throughput (bits/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Throughput per Task (rows/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Throughput per Task (bits/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesInPerSecond",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "JVM - CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Load Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_CPU_Load",
       "legendFormat": "taskmanager"
      },
      {
       "expr": "flink_jobmanager_Status_JVM_CPU_Load",
       "legendFormat": "jobmanager"
      },
      {
       "expr": "sum(flink_taskmanager_Status_JVM_CPU_Load) + sum(flink_jobmanager_Status_JVM_CPU_Load)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Threads_Count{instance=~\"$jm_instance\"}",
       "legendFormat": "jobmanager"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Threads_Count",
       "legendFormat": "taskmanager"
      },
      {
       "expr": "sum(flink_taskmanager_Status_JVM_Threads_Count) + sum(flink_jobmanager_Status_JVM_Threads_Count)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "CPU Use Time Jobmanager",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_Status_JVM_CPU_Time{instance=~\"$jm_instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Use Time Taskmanager",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_Status_JVM_CPU_Time{tm_id=~\"$tm_id\"}[1m])",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
       "legendFormat": "taskmanager"
      },
      {
       "expr": "sum(flink_jobmanager_Status_JVM_Memory_Heap_Used) + sum(flink_taskmanager_Status_JVM_Memory_Heap_Used)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Non Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
       "legendFormat": "taskmanager"
      },
      {
       "expr": "sum(flink_jobmanager_Status_JVM_Memory_NonHeap_Used) + sum(flink_taskmanager_Status_JVM_Memory_NonHeap_Used)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Storage Remote I/O (per second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(job) (flink_taskmanager_job_task_numBytesInPerSecond)",
       "legendFormat": "In "
      },
      {
       "expr": "sum by(job) (flink_taskmanager_job_task_numBytesOutPerSecond)",
       "legendFormat": "Out "
      }
     ]
    },
    {
     "title": "Storage Remote I/O Total ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(job) (flink_taskmanager_job_task_numBytesIn)",
       "legendFormat": "In "
      },
      {
       "expr": "sum by(job) (flink_taskmanager_job_task_numBytesOut)",
       "legendFormat": "Out "
      }
     ]
    },
    {
     "title": "Storage Remote I/O per Job (per second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(job_id) (flink_taskmanager_job_task_numBytesInPerSecond)",
       "legendFormat": "I - {{job_id}}"
      },
      {
       "expr": "sum by(job_id) (flink_taskmanager_job_task_numBytesOutPerSecond)",
       "legendFormat": "O - {{job_id}}"
      }
     ]
    },
    {
     "title": "Storage Remote I/O Total per Job",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(job_id) (flink_taskmanager_job_task_numBytesIn)",
       "legendFormat": "I - {{job_id}}"
      },
      {
       "expr": "sum by(job_id) (flink_taskmanager_job_task_numBytesOut)",
       "legendFormat": "O - {{job_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Memory - Shuffle Netty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_UsedMemory",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemory{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Used Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_UsedMemorySegments{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Available Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemorySegments{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (Slots & Jobs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Task Managers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_numRegisteredTaskManagers{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available Task Slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_taskSlotsAvailable{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Runnings Jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_numRunningJobs{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Job Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_fullRestarts{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "Job Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_uptime{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_id}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (Checkpoints)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "flink_jobmanager_job_totalNumberOfCheckpoints{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_id}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointFullSize{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Duration",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Back Pressure)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Is Back Pressured",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_isBackPressured{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Idle Time Ms ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_idleTimeMsPerSecond",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Checkpoint Start Delay ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_checkpointStartDelayNanos{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Checkpoint Alignment Time ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_checkpointAlignmentTime",
       "legendFormat": "{{task_name}} : {{job_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager  (Job Task - General)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number Buffers in Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBuffersInLocal{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers in Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBuffersInLocalPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers in Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBuffersInRemote{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers in Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBuffersInRemotePerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBuffersOut{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBuffersOutPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Records In",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numRecordsIn{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Records In (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numRecordsInPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Records Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numRecordsOut{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Records Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numRecordsOutPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Buffers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "In Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inPoolUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputQueueLength{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Exclusive Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputExclusiveBuffersUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Out Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_outPoolUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Output Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_outputQueueLength{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Floating Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputFloatingBuffersUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Shuffle Netty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Input Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputQueueLength",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Output Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outputQueueLength{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "In Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inPoolUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Out Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outPoolUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Floating Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputFloatingBuffersUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Exclusive Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputExclusiveBuffersUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Buffers In Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInLocal{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Buffers In Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInLocalPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Buffers In Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInRemote{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Num Buffers In Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInRemotePerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Num Bytes In Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInLocal{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Bytes In Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInLocalPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Bytes In Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInRemote{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Bytes In Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInRemotePerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  }
 ]
}