version: "3"
services:

  # zookeeper
  zookeeper:
    platform: linux/amd64
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  # kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    expose:
      - "9092"
      - "29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092, LISTENER_DOCKER_EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT, LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
     - kafka-net

  # risingwave
  risingwave:
    image: risingwavelabs/risingwave:latest
    ports:
    - 5690:5690
    - 5691:5691
    - 4566:4566
    entrypoint:
    - /risingwave/bin/risingwave
    - playground
    networks:
     - kafka-net

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mydb
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=myuser --dbname=mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "wal_level=logical" ]
    restart: always
    container_name: postgres
    networks:
     - kafka-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - "./grafana_configs/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
      - "./grafana_configs/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml"
      - "./grafana_configs:/var/lib/grafana/dashboards"
    networks:
      - kafka-net

  postgres_prepare:
    image: postgres
    depends_on: 
      - postgres
    command:
      - /bin/sh
      - -c
      - "psql postgresql://myuser:123456@host.docker.internal:5433/mydb < postgres_prepare.sql"
    volumes:
      - "./postgres_prepare.sql:/postgres_prepare.sql"      
    container_name: postgres_prepare
    restart: on-failure

  # kafka producer
  kafka-producer:
    build:
      context: .
      dockerfile: data-producers/Dockerfile
    depends_on:
     - kafka
     - zookeeper
    environment:
      KAFKA_BOOTSTRAP_SERVERS: LISTENER_DOCKER_INTERNAL://kafka:9092
    restart: always
    networks:
     - kafka-net

networks:
  kafka-net:
    driver: bridge
    name: kafka-net