image:
  file: .gitpod.Dockerfile

tasks:
  - name: Auto Bootstrap Demo
    init: |
      echo "📦 Starting demo bootstrap..."

      # STEP 0: Detect DEMO_PATH from subfolder Gitpod launch
      if [[ "$GITPOD_REPO_ROOT" != "$PWD" ]]; then
        DEMO_PATH="${PWD#$GITPOD_REPO_ROOT/}"
        echo "📁 Auto-detected DEMO_PATH: ${DEMO_PATH}"
      else
        echo "❌ Could not detect a valid demo folder."
        echo "👉 Use a Gitpod URL like:"
        echo "   https://gitpod.io/#https://github.com/user/repo/tree/main/02-simple-demos/..."
        exit 1
      fi

      echo "🚀 Starting Docker containers..."
      docker-compose up -d

      echo "⏳ Waiting for PostgreSQL to be ready..."
      for i in {1..15}; do
        if psql -h localhost -p 5432 -U pguser -d pgdb -c '\q' 2>/dev/null; then
          echo "✅ PostgreSQL is ready!"
          break
        else
          echo "Attempt $i: PostgreSQL not ready yet"
          sleep 3
        fi
      done

      echo "⏳ Waiting for RisingWave to be ready..."
      for i in {1..15}; do
        if psql -h localhost -p 4566 -U root -d dev -c '\q' 2>/dev/null; then
          echo "✅ RisingWave is ready!"
          break
        else
          echo "Attempt $i: RisingWave not ready yet"
          sleep 3
        fi
      done

      echo "🐍 Installing Python + psycopg2..."
      sudo apt-get update
      sudo apt-get install -y python3-pip
      pip3 install psycopg2-binary

      if [ -f "${DEMO_PATH}/pg_bootstrap.sql" ]; then
        echo "📦 Loading Postgres bootstrap..."
        PGPASSWORD=pgpass psql -h localhost -p 5432 -U pguser -d pgdb < ${DEMO_PATH}/pg_bootstrap.sql
      fi

      if [ -f "${DEMO_PATH}/bootstrap.sql" ]; then
        echo "📦 Loading RisingWave bootstrap..."
        psql -h localhost -p 4566 -U root -d dev < ${DEMO_PATH}/bootstrap.sql
      fi

      if [ -f "${DEMO_PATH}/data_generator.py" ]; then
        echo "⚙️ Running data generator..."
        python3 ${DEMO_PATH}/data_generator.py
      fi
    command: bash

ports:
  - port: 8088
    onOpen: open-preview
  - port: 4566
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 2181
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
