image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Services + Bootstrap
    init: |
      echo "ðŸš€ Starting Docker containers..."
      docker-compose up -d

      echo "â³ Waiting for PostgreSQL to be ready..."
      for i in {1..15}; do
        if psql -h localhost -p 5432 -U pguser -d pgdb -c '\q' 2>/dev/null; then
          echo "âœ… PostgreSQL is ready!"
          break
        else
          echo "Attempt $i: PostgreSQL not ready yet"
          sleep 3
        fi
      done

      echo "ðŸ“¦ Running pg_bootstrap.sql to create sink target tables..."
      PGPASSWORD=pgpass psql -h localhost -p 5432 -U pguser -d pgdb < 02-simple-demos/capital_markets/market_data_enrichment/pg_bootstrap.sql

      echo "â³ Waiting for RisingWave to be ready..."
      for i in {1..15}; do
        if psql -h localhost -p 4566 -U root -d dev -c '\q' 2>/dev/null; then
          echo "âœ… RisingWave is ready!"
          break
        else
          echo "Attempt $i: RisingWave not ready yet"
          sleep 3
        fi
      done

      echo "ðŸ“¦ Running bootstrap.sql to set up RisingWave schema and sinks..."
      psql -h localhost -p 4566 -U root -d dev < 02-simple-demos/capital_markets/market_data_enrichment/bootstrap.sql



ports:
  - port: 4566
    onOpen: ignore
  - port: 5691
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 2181
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 8088
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
