{
 "title": "Product Status and Profit",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Prices",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH ranked_inventory AS (\n    SELECT \n        product_id,\n        product_name,\n        inventory_window,\n        base_price,\n        new_price,\n        ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY inventory_window DESC) AS rn\n    FROM \n        dynamic_pricing_mv \n)\nSELECT \n    product_id,\n    product_name,\n    inventory_window,\n    base_price,\n    new_price\nFROM \n    ranked_inventory\nWHERE \n    rn = 1\norder by product_id;"
    }
   ]
  },
  {
   "title": "Current Product Stock Level/Status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH ranked_inventory AS (\n    SELECT \n        product_id,\n        product_name,\n        inventory_window,\n        current_inventory,\n        base_price,\n        reorder_threshold,\n        stock_level_category,\n        ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY inventory_window DESC) AS rn\n    FROM \n        product_stock_status\n)\nSELECT \n    product_id,\n    product_name,\n    inventory_window,\n    current_inventory,\n    stock_level_category\nFROM \n    ranked_inventory\nWHERE \n    rn = 1\norder by product_id;\n"
    }
   ]
  },
  {
   "title": "Demand Elasticity ",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    product_name,\n    product_id,\n    price_range,\n    SUM(total_quantity) AS total_quantity_sold,\n    SUM(total_revenue) AS total_revenue\nFROM \n    demand_elasticity\nGROUP BY \n    price_range, product_name, product_id;\n"
    }
   ]
  },
  {
   "title": "Profit per Product",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select cast(product_id as varchar), total_profit from sales_profit order by total_profit;"
    }
   ]
  },
  {
   "title": "Number of Purchases/Product",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select cast(product_id as varchar), total_purchased from sales_profit order by total_purchased;"
    }
   ]
  }
 ]
}