{
 "title": "Grid Monitoring",
 "time": { "from": "1997-05-01T00:00:00.000Z", "to": "1997-05-04T23:59:59.000Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview of All Meters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Time in Simulation ",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select max(date_trunc('minute', window_end)) from energy_per_house;"
    }
   ]
  },
  {
   "title": "Net Energy Consumption per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(total_energy) AS total_energy,\n\tdate_trunc('hour', window_end) AS hour\nFROM energy_per_house\nGROUP BY date_trunc('hour', window_end);"
    }
   ]
  },
  {
   "title": "Net Consumption This Hour",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(total_energy) AS total_energy,\n\tdate_trunc('hour', window_end) AS hour\nFROM energy_per_house\nGROUP BY date_trunc('hour', window_end)\nORDER BY hour desc LIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Net Consumption This Day",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(total_energy) AS total_energy,\n\tdate_trunc('day', window_end) AS day\nFROM energy_per_house\nGROUP BY date_trunc('day', window_end)\nORDER BY day desc LIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Net Energy Consumption per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(total_energy) AS total_energy,\n\tdate_trunc('day', window_end) AS day\nFROM energy_per_house\nGROUP BY date_trunc('day', window_end);"
    }
   ]
  },
  {
   "title": "Net Energy Consumption This Month",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "select max(month) as current_month, sum(total_energy) FROM energy_per_month GROUP BY month order by month desc limit 1;"
    }
   ]
  },
  {
   "title": "Average Energy Consumption per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH household AS(\nSELECT\n\tmeter_id,\n\tsum(total_energy) AS total_energy,\n\tdate_trunc('day', window_end) AS day\nFROM energy_per_house\nGROUP BY meter_id, date_trunc('day', window_end))\nSELECT avg(total_energy), day from household\ngroup by day"
    }
   ]
  },
  {
   "title": "Average Energy Consumption per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH household AS(\nSELECT\n\tmeter_id,\n\tsum(total_energy) AS total_energy,\n\tdate_trunc('hour', window_end) AS hour\nFROM energy_per_house\nGROUP BY meter_id, date_trunc('hour', window_end))\nSELECT avg(total_energy), hour from household\ngroup by hour;"
    }
   ]
  },
  {
   "title": "Customer Bill Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tiered Customers ",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "select customers.meter_id,\n       address,\n       current_bill,\n       total_energy AS current_energy_consumed,\n       estimated_total_bill,\n       estimated_total_energy,\n       energy_per_month.month\n       from current_bill_tiered\njoin customers on current_bill_tiered.meter_id = customers.meter_id\njoin energy_per_month on current_bill_tiered.meter_id = energy_per_month.meter_id and \n  current_bill_tiered.month = energy_per_month.month and current_bill_tiered.year = energy_per_month.year\njoin estimated_tier_cost on current_bill_tiered.meter_id = estimated_tier_cost.meter_id and\n  current_bill_tiered.month = estimated_tier_cost.month\nwhere energy_per_month.month = (select max(date_trunc('month', window_end)) from energy_per_house)\norder by month desc, meter_id\n"
      }
     ]
    },
    {
     "title": "Time of Use Customers",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "select customers.meter_id,\n       address,\n       monthly_cost as current_bill,\n       total_energy AS current_energy_consumed,\n       estimated_monthly_bill,\n       estimated_total_energy as estimated_monthly_energy,\n       energy_per_month.month from current_bill_tou\njoin customers on current_bill_tou.meter_id = customers.meter_id\njoin energy_per_month on current_bill_tou.meter_id = energy_per_month.meter_id and \n  current_bill_tou.month = energy_per_month.month and current_bill_tou.year = energy_per_month.year\njoin estimated_tou_cost on current_bill_tou.meter_id = estimated_tou_cost.meter_id and current_bill_tou.month = estimated_tou_cost.month\nwhere current_bill_tou.month = (select max(date_trunc('month', window_end)) from energy_per_house)\norder by month desc, meter_id;"
      },
      {
       "sql": {
        "columns": [
         {
          "parameters": [],
          "type": "function"
         }
        ],
        "groupBy": [
         { "property": { "type": "string" }, "type": "groupBy" }
        ],
        "limit": 50
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Monitor Meter 8",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "type": "canvas",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "select monthly_cost from current_bill_tou where meter_id = 8;"
      },
      {
       "rawSql": "select total_energy from energy_per_month where meter_id = 8;"
      },
      {
       "rawSql": "select estimated_monthly_bill, estimated_total_energy from estimated_tou_cost where meter_id = 8;"
      }
     ]
    },
    {
     "title": "Hourly Energy Consumption ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n\tSUM(total_energy) AS total_energy,\n\tdate_trunc('hour', window_end) AS month\nFROM energy_per_house\nGROUP BY meter_id, date_trunc('hour', window_end)\nHAVING meter_id = 8;"
      }
     ]
    }
   ]
  }
 ]
}